### ISSUE TITLE
Create add_constraints function

### ISSUE THREAD

**Issue by aaron0browne** [PEDSnet/pedsnetdcc#11]
See #9 for details.

**Comment by aaron0browne** [comment]
Named the functions with `foreign_keys` to distinguish from the not null and primary key functions which will do different things.

**Comment by aaron0browne** [comment]
Just waiting for some more PRs to resolve before updating the issue-11 branch and PRing it.

**Comment by murphyke** [comment]
Working on constraints branch now.

**Comment by aaron0browne** [comment]
Closed by #40.
