### ISSUE TITLE
Create `add_not_nulls` function

### ISSUE THREAD

**Issue by aaron0browne** [PEDSnet/pedsnetdcc#27]
This function will apply not null constraints to tables created by the transformation using the `create table as select` syntax. It should probably be able to get the appropriate not nulls from the stock sqlalchemy metadata from the `dmsa` package.

**Comment by aaron0browne** [comment]
Pushed issue-27 branch with the functions. Still need to write tests.

**Comment by murphyke** [comment]
Will write tests.

**Comment by aaron0browne** [comment]
Closed by #47.
