### ISSUE TITLE
Create `run_transformations` function

### ISSUE THREAD

**Issue by aaron0browne** [PEDSnet/pedsnetdcc#30]
This will aggregate all the transformations defined in the package, use them to compile `create table as select` statements, and execute them. It should also handle intelligently moving indexes, constraints, etc. to the new tables.

**Comment by aaron0browne** [comment]
I've just been thinking about this in the context of the "move primary keys" and "undo transformations" functionality, and am wondering what we are going to do with the pre-transformation tables. I think it would be much better and less full of hubris to keep them around. But we don't really want to clutter the namespace with alternately named tables. Maybe we should have a pre-transformation schema and move the tables into there. Then the "undo transformations" function would be quick and easy and perhaps we could even skip some of the index and constraint churn (I'm not sure whether the names on those objects need to be unique by database or by schema).

**Comment by murphyke** [comment]
Unique by schema I think. I think this is a good idea; as always, we just need to stay on top of the disk usage.

**Comment by murphyke** [comment]
And if we're playing with schemas, maybe we could create the transformed tables in a new temporary schema. Then we wouldn't have to drop the primary keys on the original tables. 

Here are the steps for schema `SITE_pedsnet` in that scenario:

* Create a new schema `SITE_pedsnet_transformed`.
* Create transformed tables in `SITE_pedsnet_transformed`.
* Decorate the transformed tables with primary keys and NOT NULL constraints.
* If there is a `SITE_pedsnet_backup` schema, drop it with cascade.
* Create the `SITE_pedsnet_backup` schema.
* Move the PEDSnet core tables from `SITE_pedsnet` into `SITE_pedsnet_backup` schema.
* Move the transformed PEDSnet core tables from the `SITE_pedsnet_transformed` schema to the `SITE_pedsnet` schema.
* The previous two steps can be done in a transaction.

**Comment by aaron0browne** [comment]
Agreed.

**Comment by aaron0browne** [comment]
Closed in #52
