### ISSUE TITLE
Parallel execution connection failures cause nasty bug

### ISSUE THREAD

**Issue by aaron0browne** [PEDSnet/pedsnetdcc#32]
`Statement` objects are not returned on the result queue when connections fail, because the `execute_on_conn` never gets called. This means that `StatementSet` doesn't get repopulated with the altered `Statement` objects that reflect the connection failure.

It is relatively easy to call `resq.put` in the `except` clause of the `execute` method, which fixes this bug. I also think the `StatementSet` should keep track of how many `Statements` it is expecting to `get` from the queue and error if it doesn't get the many.

**Comment by murphyke** [comment]
Will do this

**Comment by aaron0browne** [comment]
Just pushed the work I started on branch issue-32. Thanks.

**Comment by murphyke** [comment]
The work Aaron started on issue-32 is now on issue-34, rebased against current master.
