### ISSUE TITLE
pedsnetdcc defaults to json logging

### ISSUE THREAD

**Issue by murphyke** [PEDSnet/pedsnetdcc#74]
Just noticed that infomodels defaults to tty logging format, and pedsnetdcc defaults to json.  Might be better to be consistent.

**Comment by aaron0browne** [comment]
I tried pretty hard to get this right... Are you sure that you're not running them under different conditions? Is pedsnetdcc attached to a tty when it's outputting json?

**Comment by murphyke** [comment]
Aha, that looks to be the issue. I ran it using Docker with `-i` but not `-t`.
